version: "3"
services:
  web:
    build: .
    container_name: web
    expose:
      - "8080"
    volumes:
      - .:/usr/src

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
        - ./nginx:/etc/nginx/conf.d
    depends_on:
        - web